A: GENERAL WORKS
B: PHILOSOPHY. PSYCHOLOGY. RELIGION
C: AUXILIARY SCIENCES OF HISTORY
D: WORLD HISTORY AND HISTORY OF EUROPE, ASIA, AFRICA, AUSTRALIA, NEW ZEALAND, ETC.
E: HISTORY OF THE AMERICAS
F: HISTORY OF THE AMERICAS
G: GEOGRAPHY. ANTHROPOLOGY. RECREATION
H: SOCIAL SCIENCES
J: POLITICAL SCIENCE
K: LAW
L: EDUCATION
M: MUSIC AND BOOKS ON MUSIC
N: FINE ARTS
P: LANGUAGE AND LITERATURE
Q: SCIENCE
R: MEDICINE
S: AGRICULTURE
T: TECHNOLOGY
U: MILITARY SCIENCE
V: NAVAL SCIENCE
Z: BIBLIOGRAPHY. LIBRARY SCIENCE. INFORMATION RESOURCES (GENERAL)
